[windows_hosts]
10.197.0.173 ansible_user=Utilizador ansible_password=Windows10Pro

[windows_hosts:vars]
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_user=Utilizador
ansible_password=Windows10Pro
ansible_winrm_server_cert_validation=ignore
ansible_port=5985